engines:
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
      rulesets: "phpmd.xml"

  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"

  duplication:
      enabled: true
      config:
        languages:
        - php:

ratings:
  paths:
    - "src/"
    - "**.php"

exclude_paths:
- "tests/"
- "vendor/"
