language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"

services:
  - redis-server

before_install:
  - "echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini"

install:
  - "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

script:
  - "find src -type f -name '*.php' -print0 | xargs -0 -n1 php -l"
  - "composer exec -v  -- phpunit --coverage-clover build/logs/clover.xml"

after_success:
  - "vendor/bin/test-reporter"
